<a href="https://colab.research.google.com/github/anshyadavv1/ML-Models/blob/main/Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import kagglehub
path = kagglehub.dataset_download("zhaoyingzhu/heartcsv")

Using Colab cache for faster access to the 'heartcsv' dataset.

In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [99]:
import os

for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

/kaggle/input/heartcsv/Heart.csv

In [100]:
df = pd.read_csv("/kaggle/input/heartcsv/Heart.csv")

In [101]:
df.head()

   Unnamed: 0  Age  Sex     ChestPain  ...  Slope   Ca        Thal  AHD
0           1   63    1       typical  ...      3  0.0       fixed   No
1           2   67    1  asymptomatic  ...      2  3.0      normal  Yes
2           3   67    1  asymptomatic  ...      2  2.0  reversable  Yes
3           4   37    1    nonanginal  ...      3  0.0      normal   No
4           5   41    0    nontypical  ...      1  0.0      normal   No

[5 rows x 15 columns]

In [102]:
df= df.iloc[:,1:]

In [103]:
df.head()

   Age  Sex     ChestPain  RestBP  Chol  ...  Oldpeak  Slope   Ca        Thal  AHD
0   63    1       typical     145   233  ...      2.3      3  0.0       fixed   No
1   67    1  asymptomatic     160   286  ...      1.5      2  3.0      normal  Yes
2   67    1  asymptomatic     120   229  ...      2.6      2  2.0  reversable  Yes
3   37    1    nonanginal     130   250  ...      3.5      3  0.0      normal   No
4   41    0    nontypical     130   204  ...      1.4      1  0.0      normal   No

[5 rows x 14 columns]

In [104]:
from sklearn.preprocessing import LabelEncoder

In [105]:
encoder= LabelEncoder()

In [106]:
df["Thal"]= encoder.fit_transform(df["Thal"])
df["AHD"]= encoder.fit_transform(df["AHD"])
df["ChestPain"]= encoder.fit_transform(df["ChestPain"])

In [107]:
df.head()

   Age  Sex  ChestPain  RestBP  Chol  ...  Oldpeak  Slope   Ca  Thal  AHD
0   63    1          3     145   233  ...      2.3      3  0.0     0    0
1   67    1          0     160   286  ...      1.5      2  3.0     1    1
2   67    1          0     120   229  ...      2.6      2  2.0     2    1
3   37    1          1     130   250  ...      3.5      3  0.0     1    0
4   41    0          2     130   204  ...      1.4      1  0.0     1    0

[5 rows x 14 columns]

In [108]:
x= df.iloc[:,0:-1]
y= df.iloc[:,-1]

In [109]:
x

     Age  Sex  ChestPain  RestBP  Chol  ...  ExAng  Oldpeak  Slope   Ca  Thal
0     63    1          3     145   233  ...      0      2.3      3  0.0     0
1     67    1          0     160   286  ...      1      1.5      2  3.0     1
2     67    1          0     120   229  ...      1      2.6      2  2.0     2
3     37    1          1     130   250  ...      0      3.5      3  0.0     1
4     41    0          2     130   204  ...      0      1.4      1  0.0     1
..   ...  ...        ...     ...   ...  ...    ...      ...    ...  ...   ...
298   45    1          3     110   264  ...      0      1.2      2  0.0     2
299   68    1          0     144   193  ...      0      3.4      2  2.0     2
300   57    1          0     130   131  ...      1      1.2      2  1.0     2
301   57    0          2     130   236  ...      0      0.0      2  1.0     1
302   38    1          1     138   175  ...      0      0.0      1  NaN     1

[303 rows x 13 columns]

In [110]:
y

0      0
1      1
2      1
3      0
4      0
      ..
298    1
299    1
300    1
301    1
302    0
Name: AHD, Length: 303, dtype: int64

In [111]:
x_train,y_train,x_test,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [112]:
rf= RandomForestClassifier(max_samples=0.8,random_state=42)

In [113]:
rf.fit(x_train,x_test)

RandomForestClassifier(max_samples=0.8, random_state=42)

In [114]:
y_pred= rf.predict(y_train)

In [115]:
accuracy_score(y_test,y_pred)

0.9016393442622951